{
 "title": "[juju] Libvirt Metrics",
 "tags": [
  "libvirt",
  "juju"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dns_name",
    "query": "label_values(libvirt_up, dns_name)"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Important info",
   "type": "text",
   "description": "If you match very high number of DNS names you may kill your browser and/or prometheus. See \"Matching DNS names\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "content": "# Important info\n\nIf you match very high number of DNS names you may kill your browser and/or prometheus. See \"Matching DNS names\"\n\n\n"
  },
  {
   "title": "Matching DNS names",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(libvirt_up{dns_name=~\"$dns_name\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Instance Cores",
   "type": "stat",
   "description": "Number of virtual CPUs per instance, stacked",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{dns_name=~\"$dns_name\"}",
     "legendFormat": "{{domain}}: {{name}}"
    }
   ]
  },
  {
   "title": "Hypervisor Allocated Cores",
   "type": "graph",
   "description": "Total cores allocated on a given hypervisor",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,name,project_name,uuid)(libvirt_domain_info_virtual_cpus{dns_name=~\"$dns_name\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "description": "CPU time used by the domain, in seconds - rate over 1min",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total{dns_name=~\"$dns_name\"}[1m])",
     "legendFormat": "{{domain}}: {{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Cumulative Memory Usage",
   "type": "graph",
   "description": "Total memory used per hypervisor",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,name,project_name,uuid)(libvirt_domain_info_memory_usage_bytes{dns_name=~\"$dns_name\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Instance Memory Usage",
   "type": "graph",
   "description": "Instance memory usage, stacked",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_usage_bytes{dns_name=~\"$dns_name\"}",
     "legendFormat": "{{domain}}: {{name}}"
    }
   ]
  },
  {
   "title": "Max Instance Memory",
   "type": "stat",
   "description": "Maximum allowed memory per instance",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{dns_name=~\"$dns_name\"}",
     "legendFormat": "{{domain}}: {{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Instance Network Throughput",
   "type": "graph",
   "description": "Network traffic in bytes, rate over 1min, receive/transmit per instance, cumulative over all interfaces",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_receive_bytes_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "rx: {{domain}}: {{name}}"
    },
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_transmit_bytes_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "tx: {{domain}}:  {{name}}"
    }
   ]
  },
  {
   "title": "Instance Packet Rate",
   "type": "graph",
   "description": "Network traffic in packets, rate over 1min, receive/transmit per instance, cumulative over all interfaces",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_receive_packets_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "rx: {{domain}}: {{name}}"
    },
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_transmit_packets_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "tx: {{domain}}: {{name}}"
    }
   ]
  },
  {
   "title": "Cumulative Network Throughput",
   "type": "graph",
   "description": "Total network throughput rates per hypervisor, rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device, domain)(rate(libvirt_domain_interface_stats_receive_bytes_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "rx: {{domain}}"
    },
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_transmit_bytes_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "tx: {{domain}}"
    }
   ]
  },
  {
   "title": "Cumulative Packet Rate",
   "type": "graph",
   "description": "Total network throughput rates per hypervisor, rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device,domain)(rate(libvirt_domain_interface_stats_receive_packets_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "rx: {{domain}}"
    },
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_transmit_packets_total{dns_name=~\"$dns_name\"}[1m]))",
     "legendFormat": "tx: {{domain}}"
    }
   ]
  },
  {
   "title": "Instance Errors and Drops",
   "type": "graph",
   "description": "Instance errors and drops, transmit and receive. Rate over 1min",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_receive_errors_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "rx err: {{domain}}: {{name}}"
    },
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_transmit_errors_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "tx err: {{domain}}: {{name}}"
    },
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_receive_drops_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "rx drop: {{domain}}: {{name}}"
    },
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,target_device)(rate(libvirt_domain_interface_stats_transmit_drops_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "tx drop: {{domain}}: {{name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "IOPS Read",
   "type": "graph",
   "description": "Instance block dev read request rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,source_file)(rate(libvirt_domain_block_stats_read_requests_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "{{domain}}: {{name}}, {{target_device}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "graph",
   "description": "Instance block dev write request rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,source_file)(rate(libvirt_domain_block_stats_write_requests_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "{{domain}}: {{name}}, {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Read",
   "type": "graph",
   "description": "Instance block device read bytes rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,source_file)(rate(libvirt_domain_block_stats_read_bytes_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "{{domain}}: {{name}}, {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Write",
   "type": "graph",
   "description": "Instance block device write bytes rate over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(flavor,group,instance,job,project_name,source_bridge,uuid,source_file)(rate(libvirt_domain_block_stats_write_bytes_total{dns_name=~\"$dns_name\"}[1m]))\n",
     "legendFormat": "{{domain}}: {{name}}, {{target_device}}"
    }
   ]
  }
 ]
}